// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Task struct {
	ID          int64
	Due         time.Time
	Status      string
	Priority    int64
	Title       string
	Description string
}
