name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
        # Label used to access the service container
        postgres:
          # Docker Hub image
          image: postgres-alpine
          # Provide the password for postgres
          env:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: task-management-system-db
          # Set health checks to wait until postgres has started
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
                # Maps tcp port 5432 on service container to the host
                - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'
    
    - name: Wait for Postgres
      run: |
        until pg_isready -h localhost -p 5432 -U root -d task-management-system-db
        do
          echo "Waiting for postgres..."
          sleep 1
        done
    
    - name: Run mirateup
      run: make migrateup

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
