name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: task-managment-system-db  # Use the intended name with hyphens
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U root -d task-managment-system-db; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done

      - name: Build
        run: go build -v ./...

      - name: Install golang-migrate
        env:
          version: v4.15.2
          os: linux
          arch: amd64
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/$version/migrate.$os-$arch.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin
          migrate -version

      - name: Run Migrations
        run: |
          migrate -path db/migration -database "postgresql://root:secret@localhost:5432/task-managment-system-db?sslmode=disable" -verbose up

      - name: Run Tests
        run: go test -v ./...
